version: "3.8"

services:
  web:
    build: .
    container_name: noma_web
    command: gunicorn noma.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code:rw
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=noma.settings
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: noma_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
