# Generated by Django 5.2.6 on 2025-10-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='description',
        ),
    ]
