# Generated by Django 5.2.6 on 2025-10-13 10:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_banner_remove_partners_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, upload_to='gallery/%Y/%m/%d/', validators=[app.models.validate_file_type]),
        ),
    ]
