# Generated by Django 5.2.6 on 2025-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gallery_image_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovativeagriculturalpractices',
            name='image',
            field=models.ImageField(blank=True, upload_to='places_impacted/%Y/%m/%d/'),
        ),
    ]
