# Generated by Django 5.2.6 on 2025-10-13 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_innovativeagriculturalpractices_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placesimpacted',
            name='image',
        ),
        migrations.AddField(
            model_name='placesimpacted',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='places_impacted/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_governments', to='app.state'),
        ),
        migrations.AlterField(
            model_name='placesimpacted',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_impacted', to='app.localgovernment'),
        ),
        migrations.AlterField(
            model_name='placesimpacted',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_impacted', to='app.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
